version: "3.8"
services:
  db:
    image: postgres:13
    container_name: final-project-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Conestoga#2025@Final
      POSTGRES_DB: customs_freight_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
